services:
  postgres:
    image: postgres:15
    container_name: product_db
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - product-net
  product-service:
    image: psup-product/product-service
    container_name: product_service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_R2DBC_URL=jdbc:postgresql://postgres:5432/product_db
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/product_db
    networks:
      - product-net

networks:
  product-net:
    driver: bridge