services:
  postgres:
    image: postgres:15
    container_name: product_db
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - product-net
  product-service:
    image: psup-product/product-service
    container_name: product_service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/product_db
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/product_db
      - KAFKA_BROKERS=broker-1:19092,broker-2:19092,broker-3:19092
      - KAFKA_DELIVERY_TIMEOUT_MS=20000
      - KAFKA_LINGER_MS=0
      - KAFKA_REQUEST_TIMEOUT_MS=10000
      - KAFKA_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION=5
    volumes:
      - ~/Universal_Trade_Platform/logs/product-service:/root/Universal_Trade_Platform/logs/product-service
    networks:
      - product-net

networks:
  product-net:
    driver: bridge