services:
  postgres:
    image: postgres:15
    container_name: product_db
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"