server:
  port: 8080
spring:
  application:
    name: PRODUCT-SERVICE
  r2dbc:
    url: r2dbc:h2:mem:///product_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
  liquibase:
    enabled: true
    change-log: classpath:/db/main-changelog.xml
    default-schema: public
    url: jdbc:h2:mem:product_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    user: admin
    password: admin
  cloud:
    discovery:
      enabled: false
logging:
  level:
    org.springframework.data.r2dbc: DEBUG